batch_size: 32
max_epochs: 1
latent_dim: 1
kld_loss_weight: 1e-6
task: null  # or specify a name like "VAE_custom_run"

num_features: 3

pretrained: false
pretrained_path: ""
data_path: "../data/sample_train.h5"
model_dir: "../models/weight/"

timesteps: 1000
attributes:
  - ABS_f_D
  - CT_f_D_tort1
  - CT_f_A_tort1
