
# General settings
task: null  # will auto-generate if left null
data_path: "../data/sample_train.h5"
model_dir: "../models/weight/"
batch_size: 32
image_shape: [1, 64, 64, 64]  # 3D image shape. do not change unless you know what dataset you are using
attributes:
  - ABS_f_D
  - CT_f_D_tort1
  - CT_f_A_tort1

# VAE settings
vae:
  latent_dim: 4 # number of channels in the latent space
  kld_loss_weight: 0.000001
  max_epochs: 1

# FP settings
fp:
  dropout: 0.1
  max_epochs: 2

# DDPM settings
ddpm:
  timesteps: 1000
  n_feat: 64  # 512
  learning_rate: 0.000001
  max_epochs: 1
