data_path: "../data/sample_test.h5"

training:  # just for initialization of the model
  batch_size: 2
  num_batches: 2
  num_timesteps: 1000
  learning_rate: 1e-6
  max_epochs: 100

model:
  n_feat: 64
  image_shape: [1, 64, 64, 64]

attributes:
  - ABS_f_D
  - CT_f_D_tort1
  - CT_f_A_tort1

paths:
  ddpm_path: "../models/weights/ddpm.ckpt"
  vae_path: "../models/weights/vae.ckpt"
  fc_path: "../models/weights/fp.ckpt"
  output_dir: "./output_dir"
